### PR TITLE
fixed png color profiles, removed glass shard, refactored skill system

### PR DESCRIPTION
**Pull request by mruncreative**
Should solve https://github.com/lhofhansl/rangedweapons/issues/6 because I refactored the entire skill system. You can now simply turn it off.
I converted line endings to lf, so it's messy. Sorry.
After I converted to lf, I noticed it fucked up the binaries. I reset the oggs and pngs and converted the pngs to srgb with imagemagick because irrlicht threw errors about their color profile being incorrect. This is now fixed too.

Glass shards were removed because to me "shard" and "fragment" are the exact same thing.
They were dropped from glass panes and because 3 of them became a fragment, I just gave fragments 1/3 chance of dropping from panes.

And I added a German translation. Don't know how complete. I just translated the parts I was refactoring.

### CODE REVIEW

**Comment by lhofhansl** [comment]
Thanks @mruncreative 

Let's do this in separate PRs:
1. Refactoring the skill system (with white space changes only where you are making changes anyway)
2. Fixing the images
3. Converting line endings (if you really want it, I do not care that much)

**Comment by mruncreative** [comment]
Come on, doing it in separate prs now would be a giant pain.
I didn't think converting the line endings would cause such a mess. I did it with that with gitattributes file, so I thought git would handle it.
I converted them back to crlf. Now it should be easier to review.

Just test the mod before and after my changes and merge it in.

**Comment by mruncreative** [comment]
I think you could split it by doing a partial merge of the images or text files and then merge the rest.

**Comment by lhofhansl** [comment]
At least separate out the skill system.

**Comment by mruncreative** [comment]
I don't know how I do that easily.

**Comment by mruncreative** [comment]
Just merge the damn thing and I'll make new pull requests. I don't want to have to maintain a fork.

**Comment by lhofhansl** [comment]
You already have the separate commits, just cherry-pick then into another branch. Or I can do that.

[e58006e](https://github.com/lhofhansl/rangedweapons/pull/7/commits/e58006e42cded11b6614a28548fc465283113830) and [ce7954e](https://github.com/lhofhansl/rangedweapons/pull/7/commits/ce7954ede75665d374133aabb3c22df39fc018ff) change the skill's system.

**Comment by mruncreative** [comment]
Then please you do it this time. I'll figure it out how cherry-picking works in the future, promise.

**Comment by mruncreative** [comment]
No, it's not separate at all, so it throws errors when I try to use git revert or cherry pick. I give up. Just do it already.

**Comment by lhofhansl** [comment]
Sorry. Been busy. I hope to get to this soon.

**Comment by lhofhansl** [comment]
Sorry the delay... Can you remove the last three commits from this PR. Then I'll merge.

**Comment by mruncreative** [comment]
I decided I'll make my own fork. 
Toughly reviewing changes in a project where basically every single line of code has to be refactored isn't going to lead anywhere.
I also have a different vision. No hard feelings.
I had a really cool idea for an accuracy system in place of a skill system.
If I ever get done refactoring this pile of crap, you'll see it on Contentdb.

**Comment by lhofhansl** [comment]
Cool. I'm to extract some useful bits from your change. Please let me know if you disagree with that. :)

**Comment by mruncreative** [comment]
Sure. Just take it.

**Comment by mruncreative** [comment]
Look, I did it. A complete fucking rewrite.
https://gitgud.io/blut/rifles
https://content.luanti.org/packages/shaft/rifles/

**Pull request closed without merging**
